modLoader="javafml"
loaderVersion="[29,)"
issueTrackerURL="https://github.com/Darkhax-Minecraft/Better-Burning/issues"

[[mods]]
modId="betterburning"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_download}"
credits="${mod_credits}"
authors="${mod_authors}"
description='''
${mod_description}
'''

[[dependencies.betterburning]]
    modId="forge"
    mandatory=true
    versionRange="[29,)"
    ordering="NONE"
    side="SERVER"

[[dependencies.betterburning]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15]"
    ordering="NONE"
    side="SERVER"