modLoader="javafml"
loaderVersion="[35]"
issueTrackerURL="https://github.com/Darkhax-Minecraft/Better-Burning/issues"
license="LGPL v2.1"

[[mods]]
modId="betterburning"
updateJSONURL="https://updates.blamejared.com/get?n=betterburning&gv=1.16.4"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_download}"
credits="${mod_credits}"
authors="${mod_authors}"
description='''
${mod_description}
'''

[[dependencies.betterburning]]
    modId="forge"
    mandatory=true
    versionRange="[35]"
    ordering="NONE"
    side="SERVER"

[[dependencies.betterburning]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="SERVER"